//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string ErrorMsg { get; set; }
        public string StackTrace { get; set; }
        public string Location { get; set; }
        public string LoginUser { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
