//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Deleted_At { get; set; }
        public Nullable<int> Deleted_By { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FatherGuardians { get; set; }
    }
}
